# Generated by Django 4.0.6 on 2022-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end_adv_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Web'), (2, 'Desktop'), (3, 'Mobile'), (4, 'Cloud'), (5, 'Design'), (6, 'Architecture')], default=0),
        ),
    ]
